// Code generated by "stringer -type ExitCode -trimprefix ExitCode --linecomment"; DO NOT EDIT.

package flargs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodeSuccess-0]
	_ = x[ExitCodeGenericError-1]
	_ = x[ExitCodeMisuseOfBuiltIns-2]
}

const _ExitCode_name = "Successwtf dudeMisuseOfBuiltIns"

var _ExitCode_index = [...]uint8{0, 7, 15, 31}

func (i ExitCode) String() string {
	if i >= ExitCode(len(_ExitCode_index)-1) {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[i]:_ExitCode_index[i+1]]
}
